/// 꿈의 도시 — 직업·테크트리 건물 정의 (SimCity + 방치형 하이브리드).
enum DreamCityBranch {
  foundation('기초 마을', '🏘️', 0xFF64748B),
  scholar('학자', '📖', 0xFF3B82F6),
  scientist('과학자', '🔬', 0xFF06B6D4),
  doctor('의사', '⚕️', 0xFF10B981),
  engineer('개발자', '💻', 0xFF8B5CF6),
  artist('예술가', '🎨', 0xFFEC4899),
  chef('요리사', '👨‍🍳', 0xFFF59E0B),
  athlete('운동선수', '⚽', 0xFFEF4444),
  astronaut('우주비행사', '🚀', 0xFF6366F1);

  final String labelKo;
  final String emoji;
  final int colorValue;

  const DreamCityBranch(this.labelKo, this.emoji, this.colorValue);
}

class DreamCityBuildingDef {
  final String id;
  final String nameKo;
  final String emoji;
  final DreamCityBranch branch;
  final int tier;
  final int blockCost;
  final List<String> requiresIds;
  final int gridX;
  final int gridY;
  final double heightUnits;
  final String kidDreamLine;

  const DreamCityBuildingDef({
    required this.id,
    required this.nameKo,
    required this.emoji,
    required this.branch,
    required this.tier,
    required this.blockCost,
    this.requiresIds = const [],
    required this.gridX,
    required this.gridY,
    this.heightUnits = 1.0,
    required this.kidDreamLine,
  });
}

/// 전체 건물 카탈로그 (테크트리).
const dreamCityCatalog = <DreamCityBuildingDef>[
  // 기초
  DreamCityBuildingDef(
    id: 'tent',
    nameKo: '공부 텐트',
    emoji: '⛺',
    branch: DreamCityBranch.foundation,
    tier: 1,
    blockCost: 5,
    gridX: 1,
    gridY: 1,
    heightUnits: 0.6,
    kidDreamLine: '첫 집중으로 꿈이 시작돼요',
  ),
  DreamCityBuildingDef(
    id: 'study_room',
    nameKo: '나만의 공부방',
    emoji: '🏠',
    branch: DreamCityBranch.foundation,
    tier: 2,
    blockCost: 25,
    requiresIds: ['tent'],
    gridX: 1,
    gridY: 2,
    heightUnits: 1.2,
    kidDreamLine: '매일 조금씩 쌓이는 습관',
  ),
  DreamCityBuildingDef(
    id: 'town_square',
    nameKo: '마을 광장',
    emoji: '🌳',
    branch: DreamCityBranch.foundation,
    tier: 3,
    blockCost: 50,
    requiresIds: ['study_room'],
    gridX: 2,
    gridY: 1,
    heightUnits: 0.8,
    kidDreamLine: '친구와 함께 쉬는 공간',
  ),
  DreamCityBuildingDef(
    id: 'city_hall',
    nameKo: '꿈 시청',
    emoji: '🏛️',
    branch: DreamCityBranch.foundation,
    tier: 4,
    blockCost: 120,
    requiresIds: ['town_square'],
    gridX: 2,
    gridY: 2,
    heightUnits: 2.0,
    kidDreamLine: '우리 마을의 중심',
  ),
  // 학자
  DreamCityBuildingDef(
    id: 'book_nook',
    nameKo: '책 읽는 코너',
    emoji: '📕',
    branch: DreamCityBranch.scholar,
    tier: 1,
    blockCost: 30,
    requiresIds: ['study_room'],
    gridX: 0,
    gridY: 1,
    kidDreamLine: '책벌레의 첫 걸음',
  ),
  DreamCityBuildingDef(
    id: 'library',
    nameKo: '마을 도서관',
    emoji: '📚',
    branch: DreamCityBranch.scholar,
    tier: 2,
    blockCost: 70,
    requiresIds: ['book_nook'],
    gridX: 0,
    gridY: 2,
    heightUnits: 1.6,
    kidDreamLine: '지식이 쌓이는 곳',
  ),
  DreamCityBuildingDef(
    id: 'university',
    nameKo: '꿈 대학교',
    emoji: '🎓',
    branch: DreamCityBranch.scholar,
    tier: 3,
    blockCost: 200,
    requiresIds: ['library', 'city_hall'],
    gridX: 0,
    gridY: 3,
    heightUnits: 2.4,
    kidDreamLine: '큰 꿈을 키우는 캠퍼스',
  ),
  // 과학자
  DreamCityBuildingDef(
    id: 'lab_basic',
    nameKo: '과학 실험실',
    emoji: '🧪',
    branch: DreamCityBranch.scientist,
    tier: 1,
    blockCost: 40,
    requiresIds: ['study_room'],
    gridX: 3,
    gridY: 1,
    kidDreamLine: '호기심이 불꽃이 되요',
  ),
  DreamCityBuildingDef(
    id: 'research_center',
    nameKo: '연구 센터',
    emoji: '🔭',
    branch: DreamCityBranch.scientist,
    tier: 2,
    blockCost: 90,
    requiresIds: ['lab_basic'],
    gridX: 3,
    gridY: 2,
    heightUnits: 1.8,
    kidDreamLine: '발견의 연구소',
  ),
  DreamCityBuildingDef(
    id: 'observatory',
    nameKo: '천문대',
    emoji: '🌌',
    branch: DreamCityBranch.scientist,
    tier: 3,
    blockCost: 180,
    requiresIds: ['research_center'],
    gridX: 3,
    gridY: 3,
    heightUnits: 2.2,
    kidDreamLine: '별을 향한 눈',
  ),
  // 의사
  DreamCityBuildingDef(
    id: 'clinic',
    nameKo: '건강 클리닉',
    emoji: '🩺',
    branch: DreamCityBranch.doctor,
    tier: 1,
    blockCost: 45,
    requiresIds: ['town_square'],
    gridX: 1,
    gridY: 0,
    kidDreamLine: '다치는 친구를 돕고 싶어요',
  ),
  DreamCityBuildingDef(
    id: 'hospital',
    nameKo: '마을 병원',
    emoji: '🏥',
    branch: DreamCityBranch.doctor,
    tier: 2,
    blockCost: 100,
    requiresIds: ['clinic'],
    gridX: 2,
    gridY: 0,
    heightUnits: 1.7,
    kidDreamLine: '생명을 지키는 의사',
  ),
  DreamCityBuildingDef(
    id: 'medical_univ',
    nameKo: '의대',
    emoji: '💊',
    branch: DreamCityBranch.doctor,
    tier: 3,
    blockCost: 220,
    requiresIds: ['hospital', 'university'],
    gridX: 3,
    gridY: 0,
    heightUnits: 2.0,
    kidDreamLine: '최고의 의료진 양성',
  ),
  // 개발자
  DreamCityBuildingDef(
    id: 'pc_room',
    nameKo: '코딩 교실',
    emoji: '🖥️',
    branch: DreamCityBranch.engineer,
    tier: 1,
    blockCost: 35,
    requiresIds: ['study_room'],
    gridX: 4,
    gridY: 1,
    kidDreamLine: '앱을 만드는 꿈',
  ),
  DreamCityBuildingDef(
    id: 'it_tower',
    nameKo: 'IT 타워',
    emoji: '🏢',
    branch: DreamCityBranch.engineer,
    tier: 2,
    blockCost: 85,
    requiresIds: ['pc_room'],
    gridX: 4,
    gridY: 2,
    heightUnits: 2.5,
    kidDreamLine: '스타트업의 심장',
  ),
  DreamCityBuildingDef(
    id: 'startup_campus',
    nameKo: '스타트업 캠퍼스',
    emoji: '🚀',
    branch: DreamCityBranch.engineer,
    tier: 3,
    blockCost: 250,
    requiresIds: ['it_tower', 'city_hall'],
    gridX: 4,
    gridY: 3,
    heightUnits: 2.8,
    kidDreamLine: '세상을 바꾸는 서비스',
  ),
  // 예술가
  DreamCityBuildingDef(
    id: 'art_class',
    nameKo: '미술 교실',
    emoji: '🖌️',
    branch: DreamCityBranch.artist,
    tier: 1,
    blockCost: 32,
    requiresIds: ['town_square'],
    gridX: 0,
    gridY: 0,
    kidDreamLine: '색으로 표현하는 마음',
  ),
  DreamCityBuildingDef(
    id: 'gallery',
    nameKo: '갤러리',
    emoji: '🖼️',
    branch: DreamCityBranch.artist,
    tier: 2,
    blockCost: 75,
    requiresIds: ['art_class'],
    gridX: 4,
    gridY: 0,
    heightUnits: 1.4,
    kidDreamLine: '작품을 전시해요',
  ),
  DreamCityBuildingDef(
    id: 'concert_hall',
    nameKo: '공연장',
    emoji: '🎭',
    branch: DreamCityBranch.artist,
    tier: 3,
    blockCost: 160,
    requiresIds: ['gallery'],
    gridX: 4,
    gridY: 4,
    heightUnits: 2.1,
    kidDreamLine: '무대 위의 주인공',
  ),
  // 요리사
  DreamCityBuildingDef(
    id: 'kitchen',
    nameKo: '꿈 주방',
    emoji: '🍳',
    branch: DreamCityBranch.chef,
    tier: 1,
    blockCost: 28,
    requiresIds: ['tent'],
    gridX: 2,
    gridY: 3,
    kidDreamLine: '맛있는 응원 도시락',
  ),
  DreamCityBuildingDef(
    id: 'cafe',
    nameKo: '공부 카페',
    emoji: '☕',
    branch: DreamCityBranch.chef,
    tier: 2,
    blockCost: 65,
    requiresIds: ['kitchen'],
    gridX: 1,
    gridY: 3,
    heightUnits: 1.3,
    kidDreamLine: '집중과 휴식의 균형',
  ),
  DreamCityBuildingDef(
    id: 'restaurant',
    nameKo: '레스토랑',
    emoji: '🍽️',
    branch: DreamCityBranch.chef,
    tier: 3,
    blockCost: 140,
    requiresIds: ['cafe', 'town_square'],
    gridX: 2,
    gridY: 4,
    heightUnits: 1.6,
    kidDreamLine: '셰프의 꿈',
  ),
  // 운동선수
  DreamCityBuildingDef(
    id: 'playground',
    nameKo: '운동 놀이터',
    emoji: '🏃',
    branch: DreamCityBranch.athlete,
    tier: 1,
    blockCost: 22,
    requiresIds: ['tent'],
    gridX: 3,
    gridY: 4,
    kidDreamLine: '몸도 마음도 건강하게',
  ),
  DreamCityBuildingDef(
    id: 'stadium',
    nameKo: '스타디움',
    emoji: '🏟️',
    branch: DreamCityBranch.athlete,
    tier: 2,
    blockCost: 110,
    requiresIds: ['playground'],
    gridX: 1,
    gridY: 4,
    heightUnits: 1.9,
    kidDreamLine: '팀워크와 열정',
  ),
  // 우주 (과학+학자 합류)
  DreamCityBuildingDef(
    id: 'space_center',
    nameKo: '우주 센터',
    emoji: '🛸',
    branch: DreamCityBranch.astronaut,
    tier: 1,
    blockCost: 280,
    requiresIds: ['observatory', 'research_center'],
    gridX: 0,
    gridY: 4,
    heightUnits: 2.6,
    kidDreamLine: '우주비행사의 꿈',
  ),
  DreamCityBuildingDef(
    id: 'rocket_pad',
    nameKo: '로켓 발사대',
    emoji: '🚀',
    branch: DreamCityBranch.astronaut,
    tier: 2,
    blockCost: 450,
    requiresIds: ['space_center', 'startup_campus'],
    gridX: 3,
    gridY: 0,
    heightUnits: 3.2,
    kidDreamLine: '가장 높은 꿈',
  ),
];

DreamCityBuildingDef? dreamCityDefById(String id) {
  for (final d in dreamCityCatalog) {
    if (d.id == id) return d;
  }
  return null;
}

List<DreamCityBuildingDef> dreamCityByBranch(DreamCityBranch b) =>
    dreamCityCatalog.where((d) => d.branch == b).toList();
